### PR TITLE
Fix trackSelector declaration

### PR DESCRIPTION
**Pull request by cmdcolin**
This follows up on #1 and fixes the trackselector declaration, it was specified wrong in the previous PR

### CODE REVIEW

**Comment by cmdcolin** [comment]
will rebase against master before can merge

**Comment by cmdcolin** [comment]
@putmantime should be ready now I think

**Comment by putmantime** [comment]
@cmdcolin Fantastic!  Merged and it works great.  I pushed it to the http://34.204.101.171/.  Feel free to take a look at the new interface and tell me what you think.  I have some work to do with tool tips and guides but will be mapping wikigenomes.org to it soon.

**Comment by cmdcolin** [comment]
Nice, I think it is looking good!

for what it's worth, I definitely think that the tight WDQS integration that my changes added are the "way to go". trying to invent a lot of infrastructure for duplicated managing the feature data seems like it is antithetical


I guess my next sort of question is that I am still a little hung up on the fact that all genomes are predefined and stored in the git repository. it seems a little inflexible and also makes the git repo really big. it would be sweet if somehow all species were defined on wikidata itself and species data didn't need to be stored in the git repo at all!

**Comment by cmdcolin** [comment]
Also personal preference but I would make the jbrowse iframe a little taller :)

**Comment by cmdcolin** [comment]
Also I havent' tested editing stuff using the UI but I could definitely give that a shot. I have gotten into wikipedia editing lately :)

**Comment by cmdcolin** [comment]
looks like new site live now :)

**Pull request merged**
